/**
 * @description 面向 Agent 客户端的 MCP / Codex 审批配置片段生成器。
 *
 * 在 Hub 批次 `approvalToken` 与写操作门禁齐备后，Codex 侧应使用 `auto`，
 * 由服务端租约/确认策略承接风险，而不是客户端逐工具 `prompt`。
 */
export class ProjectMcpAgentConfig {
    /** @description 推荐的 Codex 审批模式（门禁齐备后）。 */
    public static readonly recommendedCodexApprovalMode = 'auto' as const;

    /**
     * @description 生成 Codex `config.toml` 片段（不写盘）。
     * @param options 可选覆盖。
     * @returns TOML 文本。
     */
    public static buildCodexToml(options: {
        readonly approvalMode?: 'auto' | 'writes' | 'prompt';
        readonly mcpServerName?: string;
        readonly mcpUrl?: string;
    } = {}): string {
        const approvalMode = options.approvalMode ?? ProjectMcpAgentConfig.recommendedCodexApprovalMode;
        const serverName = options.mcpServerName ?? 'peanut-cocos-mcp';
        const lines = [
            `# Generated by peanut-plugin-core ProjectMcpAgentConfig`,
            `# Prefer server-side approvalToken / resource lease over client prompts.`,
            `default_tools_approval_mode = "${approvalMode}"`,
        ];
        if (typeof options.mcpUrl === 'string' && options.mcpUrl.trim().length > 0) {
            lines.push('');
            lines.push(`[mcp_servers.${serverName}]`);
            lines.push(`url = "${options.mcpUrl.trim()}"`);
        }
        return `${lines.join('\n')}\n`;
    }

    /**
     * @description 生成 Cursor / Claude `mcpServers` JSON 对象。
     * @param mcpUrl Hub HTTP URL。
     * @param serverName 服务器名。
     * @returns 可合并进客户端配置的对象。
     */
    public static buildCursorMcpServers(
        mcpUrl: string,
        serverName = 'peanut-cocos-mcp',
    ): { readonly mcpServers: Readonly<Record<string, { readonly url: string }>> } {
        if (typeof mcpUrl !== 'string' || mcpUrl.trim().length === 0) {
            throw new Error('project_mcp_agent_config_url_required');
        }
        return {
            mcpServers: {
                [serverName]: { url: mcpUrl.trim() },
            },
        };
    }
}
